Sprint 2 review demo for customer (#17)
* Add database support for indicator goals

* Initial sketch of gdc.

* More GDC work.

* Add query to get all data series values for a given municipality.

* Small fixes for handling.

* Start of GDC goals queries.

* First pass at indicator score calculation customization.

* Detailed calculation methods per dataseries

* Added more ranges and domains to data properties.

* More UNSDG <-> SDG integration

* Finalize score computation.

* Hook up external goal setting

* Add correlation generator.

* Small usability improvement for correlation generator.

* Correlations for just Japan and South Korea.

* Add correlations to ontology.

* Add dummy data tag to correlations

* Hook up correlation API.

* Fix compilation errors.

* Update test util.

* Small fixes

* Better comments

* Pretty print json responses in test util

* Fix correlation direction.

* Normalise naming to 'indicator'.

* Small ontology fixup

* More sophisticated data generator.

* KPI fix.

* GDC fixes

* Util fixes.

* Fix for INV_... calculation method predictions.

* Slightly better data generation.

* Fix missing data series -> kpi hookup in ontology

* Use a more complete post test for gdc.

* Generate data until "deadline".

* Remove some debug logging.

* Add better comments to the correlation API.

* Generate data for both Oslo and Trondheim

* More modular tester.

* Ran prettier.

* Eslint fixes

* Add target CAGR to indicator score.

* Add more links to correlations xml.

* Some better comments.

* Clarify some comments wrt. when the completion prediction might fail.

* Disable completion prediction for bools.

* Fix linting errors.

* More linting errors (sigh...)

* Provide goal extraction endpoint.

* Provide more accessible KPI / dataseries information from GDC endpoint.

* Add some documentation for what CAGR stands for, as well as fixing a small typo.

* Demos for sprint 2.

* Add setup script.

* Readme for demos.

* remove undefined reference to u4ssc

Co-authored-by: Jørgen Rosager <joergen.rosager@gmail.com>